project:
  output-dir: docs
  execute-dir: project
  # The "*.qmd" is necessary to describe which files should be rendered, 
  # so if you've got some .Rmd files as well, you need to add another line 
  # with "*.Rmd" to make sure they are rendered (if you want them to be).
  # Plus the !refs/ explicitly excludes that folder from the render.
  render: 
    - "*.qmd"
    - "!refs/"

toc: true
toc-depth: 4
toc-title: "Table of contents"
number-sections: true
highlight-style: github
link-citations: true

format:
  pdf: 
    pdf-engine: xelatex
    documentclass: scrreprt
    papersize: a4
    fontsize: 12pt
    mainfont: Libertinus Serif
    sansfont: Libertinus Sans
    monofont: Libertinus Mono
    # mathfont: Asana Math
    mathfont: Libertinus Math
    linestretch: 1.25
    template-partials: 
      - _extensions/partials/before-body.tex
    include-in-header:
      text: |
       \usepackage{physics}
       \setkomafont{chapter}{\fontsize{16}{18}\selectfont}
       \setkomafont{section}{\fontsize{14}{16}\selectfont}

  docx:
    reference-doc: etc/template-qmd.docx
    number-sections: true
    filters:
    - _extensions/study-summary.lua
    - _extensions/color-comment.lua
    
  html: default

execute: 
  message: false
  warning: false
  echo: false
  